### ISSUE TITLE
Dynamixel monitoring during movement issue

### ISSUE THREAD

**Issue by gib-gif** [Interbotix/dynamixelsdk_xsarm_examples#1]
Robot Model: Interbotix px150 
Dynamixels: XL430-W250-T
OS: Ubuntu 20.04.2
ROS Distro: Noetic

In short, I am trying to instruct the arm to go through a series of movements while capturing data like effort or temperature from the motors. Using the python example offered here I was able to get back the data I wanted, but I had hoped to control the arm using ROS commands built into a python file. When I set the arm moving with a separate python file of ROS commands, I tried to run the python example with all the write functions commented out but this command failed with the error:
[TxRxResult] Incorrect status packet!
It would seem to me that while using the interbotix_xsarm_control node, I cannot simultaneously communicate with the dynamixels. Is this correct or have I made a mistake? Is there any way around this?
Any help would be greatly appreciated.

**Comment by lukeschmitt-tr** [comment]
HI @gib-gif! Because you are trying to interact with ROS, I would recommend using the Python demo scripts in the [interbotix_ros_xsarms repo](https://github.com/Interbotix/interbotix_ros_manipulators/tree/main/interbotix_ros_xsarms). These demos allow you to work with the X-Series arms SDK using ROS. The xs_sdk provides wrappers that communicate directly with the Dynamixels, allowing you to command the motors through ROS. There, you will find simple Python scripts that take the arm through a series of poses and gripper states. Something like [bartender.py](https://github.com/Interbotix/interbotix_ros_manipulators/blob/21683026ed7069cbb7aa6001e808a10f0f2d7670/interbotix_ros_xsarms/examples/python_demos/bartender.py) would be great to start with.

To see the underlying ROS commands, you can check out the [arm module](https://github.com/Interbotix/interbotix_ros_toolboxes/blob/2fabcbf4b9f48ac917ef9ce4985419c0c4316763/interbotix_xs_toolbox/interbotix_xs_modules/src/interbotix_xs_modules/arm.py) from the [interbotix_ros_toolboxes repo](https://github.com/Interbotix/interbotix_ros_toolboxes) (also written in Python).

**Comment by gib-gif** [comment]
Ok, thank you
